baseURL: '/'
languageCode: 'en-us'
title: 'ELBY css'

theme: elby 
staticDir: "/themes/elby/static"

outputs: 
  home: [ "HTML", "JSON"]
  page: [ "HTML", "JSON"]
  section: [ "HTML", "JSON"]
  list: [ "HTML", "JSON"]
  taxonomies: [ "HTML", "JSON"]