baseURL: '/'
languageCode: 'en-us'
title: 'ELBY css'

theme: elby 
staticDir: "/themes/elby/static"

params:
  version: 0.1.2

outputs: 
  home: [ "HTML"]
  page: [ "HTML"]
  section: [ "HTML"]
  list: [ "HTML"]
  taxonomies: [ "HTML"]